#! /bin/sh

function the_cleanup {
rm -rf ~/.vimrc
rm -rf ~/.vim
}

function the_vaudeville_vundler {
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
}

function the_symlink {
ln -s ~/dotfiles/.bash_profile ~/.bash_profile
ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.gemrc ~/.gemrc
ln -s ~/dotfiles/.git ~/.git
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.gitignore ~/.gitignore
ln -s ~/dotfiles/.irbrc ~/.irbrc
ln -s ~/dotfiles/.rspec ~/.rspec
ln -s ~/dotfiles/.sqliterc ~/.sqliterc
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.vimrc ~/.vimrc
}

function the_heist {
vim +BundleInstall +qall
}

function the_brew {
brew update
brew install ctags-exuberant git rbenv ruby-build tmux macvim sqlite rbenv-gem-rehash bash-completion
}

function run {
the_cleanup
the_vaudeville_vundler
the_symlink
the_brew
the_heist
}

run
